### ISSUE TITLE
Allow different time/chill lengths

### ISSUE THREAD

**Issue by alexdrans** [tiaanduplessis/pomd#10]
I use 50/10/50/25 instead of 25/5, so it would be useful to be able to configure this.

I'm thinking;

```
🍅 start -t 50m -c 10m -t 50m -c 25m --loop
```

and the timer will loop 50/10/50/25 infinitely.

Could also potentially work for

```
🍅 start -t 50m -c 10m -t 50m -c 25m -t 30m -c 10m --loop
```

Essentially, iterate any combination of -t and -c, and if..

```
🍅 start -t 50m -t 60m -c 10m
```

is entered, throw an error, saying that time can't follow time, chill can't follow chill

What do you think, useful general feature? I'll PR it myself this weekend.

**Comment by tiaanduplessis** [comment]
Sound like a awesome addition. Looking forward to the PR. 👍

**Comment by alexdrans** [comment]
@tiaanduplessis I haven't forgotten about this - just very busy! It's a long weekend in the UK so I'm hoping to get it done.

**Comment by tiaanduplessis** [comment]
No problem man. There's no rush 😄

**Comment by alexdrans** [comment]
@tiaanduplessis Any tips on how to test vorpal? 🤔 Seems pretty awkward,
